### ISSUE TITLE
ROS usage issue

### ISSUE THREAD

**Issue by LancerXE** [rayguan97/GANav-offroad#10]
Hi, Thanks for this great work!
May I ask the which ROS version you used to test the algorithm?
I'm currently using Ubuntu 16.04 with ROS kinetic, but I got a bit confused whether to run the code in conda environment with python 3.7 or use python 2.7 which comes with ROS?

**Comment by rayguan97** [comment]
The code is mostly run on python3. The part that uses ROS is basically interfacing the code — adding a publisher and subscriber.

Let me know if run into any issues.


________________________________
From: LancerXE ***@***.***>
Sent: Tuesday, July 5, 2022 8:24:11 AM
To: rayguan97/GANav-offroad ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rayguan97/GANav-offroad] ROS usage issue (Issue #10)


Hi, Thanks for this great work!
May I ask the which ROS version you used to test the algorithm?
I'm currently using Ubuntu 16.04 with ROS kinetic, but I got a bit confused whether to run the code in conda environment with python 3.7 or use python 2.7 which comes with ROS?

**Comment by LancerXE** [comment]
I think it's because the default python version for ROS kinetic is Python 2.7, so it get many errors when running the rosrun command. And although I found a way to solve the cv2 issue mentioned above, it still comes out with other errors:

> ImportError: No module named mmseg.apis

This error occurs because the mmcv is installed in conda environment in Python 3.7, does that means I need to install mmcv also for Python 2.7? Or may be there's another way to solve this compatibility issue between Python 3 and Python 2.

**Comment by rayguan97** [comment]
I double checked my env. I run it with conda env with python 3. I suggest that you create the env according to the instruction, and install mmcv and GANav. If it still need anything from ROS, maybe try sourcing the ROS code and then activate the conda env.

Hope this would resolve your issue. Please let me know if you still have trouble.

**Comment by LancerXE** [comment]
Hi, thanks for your reply!
I have tested the algorithm on two computers, and both of them get an error about the version of mmcv should be higher than 1.4.1 and lower than 1.5.0, so the command to install the mmcv in introduction may need to be changed to:
`pip install mmcv-full==1.5.0 -f
 https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html`
or:`pip install mmcv-full==1.5.0 -f 
https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html`

**Comment by rayguan97** [comment]
Thanks for the notice! Another way is to change mmseg/__ini__.py, line 5 and 6. It’s only a hard-coded check and Usually mmcv have good backwards compatibility.

**Comment by LancerXE** [comment]
Hi, I read the paper you put in the introduction, may I ask how did you get these ground truth?
![paper1](https://user-images.githubusercontent.com/98766249/178765880-4e9953a6-911a-435c-ad4d-ff94e6d0531f.PNG)
Cause after the dataset processing, I just got processed annotations like this:
![paper](https://user-images.githubusercontent.com/98766249/178766246-2b313fc4-c983-4e14-a042-c391e253b68e.PNG)

**Comment by rayguan97** [comment]
I’m not sure I follow your question. Do you mean the set of colors are different, or you mean you are trying to locate the two images shown in the figure from the paper.

After processing you will have the annotations in both colors and ids. The original annotations are provided by the dataset, and we just process the annotations for our segmentation task.

**Comment by LancerXE** [comment]
Sorry for confusing. 
It's because I got all black images after processing as you can see in the above screenshot. I know the processed ground truth should look similar to the images shown in the paper, I'm not sure if I did something wrong during the processing.

**Comment by rayguan97** [comment]
I see. That’s perfectly fine since those are ID of the labels so they have very low rgb values. They are all dark pixels which is hard to pick up by eyes.

**Comment by LancerXE** [comment]
Thanks for your reply!
I have read the code, may I ask does it only need to change the parameter 'img_size' in code if I would like to train my own dataset?

**Comment by rayguan97** [comment]
Yes. The you only need to change the img_size and follow the config format to make any changes. I believe the crop_size the size that the network takes during training (the weight), so you can adjust the crop_size accordingly based on how large you want the network be, with a reasonable range. During inference time, it will infer the entire image of img_size.

**Comment by rayguan97** [comment]
I'm closing this issue as this is regarding ROS usage. Please start another issue if there are more questions.

**Comment by PaulDurai25** [comment]
Thanks in advance.... in ROS environment i am getting horizontal patch which is not classifying properly... i changed the dim(688,550) to other values again the same problem...can you please suggest the solution for this... i have attached the snapshot of the result for your better understanding... 
![Screenshot from 2022-09-08 09-58-31](https://user-images.githubusercontent.com/112052669/189036337-2143250c-dfe3-4f07-910a-202518d5d649.png)
