### ISSUE TITLE
RuntimeError: Output 0 of ReshapeAliasBackward0 is a view and is being modified inplace.

### ISSUE THREAD

**Issue by christinewz** [rayguan97/GANav-offroad#11]
Hi, 

Thanks for your work! I encountered an issue when running the command to train a model with your methods: 

> python ./tools/train.py ./configs/ours/ganav_group6_rugd.py

> python ./tools/train.py ./configs/ours/ganav_group6_rellis.py 

Both of the commands prompt this error:
![image](https://user-images.githubusercontent.com/75345501/178755771-08e55246-2549-4f5e-b8e0-57ab6b9e88a7.png)

I am still new to this topic, could you kindly let me know how to solve this problem?

**Comment by rayguan97** [comment]
Hi,

I have never seen this issue before. I want to make sure I have all the packages version correct. 

In addition, I found this website that might help you resolve the issue: https://stackoverflow.com/questions/72498093/when-using-attention-augmented-convolution-layer-from-source-code-in-resunet-g#:~:text=RuntimeError%3A%20Output%200%20of%20ReshapeAliasBackward0,out%2Dof%2Dplace%20one.

Those scripts essentially process the data, and the logic is straightforward. In worst case, you can modify the line that gives your the error as long as you make sure the logic is not changed.

**Comment by rayguan97** [comment]
I have never seen this issue before. Please make sure you have the correct version of the packages.

In addition, I found this website that might resolve your issue: https://stackoverflow.com/questions/72498093/when-using-attention-augmented-convolution-layer-from-source-code-in-resunet-g#:~:text=RuntimeError%3A%20Output%200%20of%20ReshapeAliasBackward0,out%2Dof%2Dplace%20one.

Could you give more details on the error? Which line caused it and the entire error message would be helpful.

**Comment by rayguan97** [comment]
Thanks! In fact you only need to show the last image, which shows error and which line has the error.

It seems that in transnet.py, line 179, you have a in-place operator. I can not reproduce this error, but you can simply change it to a out-of-place multiplication operator.

**Comment by iliabaranov** [comment]
Bizarrely had this issue as well, all it took to fix it was to change 
```
q *= self.scale
```
to 
```
q = q*self.scale
```

**Comment by rayguan97** [comment]
Thank you for the fix -- I will update this change.
