### ISSUE TITLE
Check point file

### ISSUE THREAD

**Issue by LancerXE** [rayguan97/GANav-offroad#13]
Hi,  thanks again for this great work!
May I ask how do you generate the checkpoint file (.pth)? I'm trying to train the model with my own dataset, the training process went well. But in the testing process, I'm confused about whether to use the pre-trained model you provided or if I need to generate my own checkpoint file?
Thank you!

**Comment by rayguan97** [comment]
You need to use your own checkpoint if you train the model by yourself. The model should be saved by default in "./work_dirs/"

**Comment by LancerXE** [comment]
Thanks for your reply!
I tried to load the pre-trained model in the training process but after training in the "./work_dirs/" there is just a log and a .py file, so I don't have a new check point file generated:
![捕获](https://user-images.githubusercontent.com/98766249/180983504-dc5b364c-28ce-499d-a9f0-f64b029164ce.PNG)
Is it because I loaded the pre-trained model?

**Comment by rayguan97** [comment]
How fast is your training progress? Sometimes when you load a pre-trained model, it would store the number of iterations. If your config is 240k iters and the pre-trained model has been trained for 240k iters, then it would not be trained at all. In that case, you should increase your config to 360k, for example, so the model can be trained for another 120k iters.

**Comment by LancerXE** [comment]
I think it's 160k as a default, cause I didn't change the file '/configs/base/schedule/schedule_160k.py' for training, in the training process it did have a training record like this:
![train](https://user-images.githubusercontent.com/98766249/180987105-9229c2c8-d3de-4b22-bc15-b1dfab99b9bf.PNG)
Should I increase the iterations in this case?

**Comment by rayguan97** [comment]
In this case, you don't need to increase the iterations. How long have you been training? The checkpoint is generated every few iterations. You can only see the py file and log file in the beginning.

**Comment by LancerXE** [comment]
Thank you so much, now I understand it is because the training time is not enough since the google colab cut the connection if there is no interaction in 90 minutes.

**Comment by PaulDurai25** [comment]
![int Error](https://user-images.githubusercontent.com/112052669/186825966-55304ad1-8a8a-472b-a86f-e361e235ffa4.png)

Hai, Updated Ganav run error. how to rectify this?

**Comment by rayguan97** [comment]
It has not problems on my end, can you make sure you have everything updated? 

I suggest that you check the config file and make sure that the in_channels for decoder_head is an array. In this case I think the in_channels variable is an integer, which caused the issue. Make sure you use the latest ganav_rellis_6.py for config, and the corresponding pth file on the google drive for the checkpoint.

**Comment by PaulDurai25** [comment]
Thank you, how to run ganav_rellis.py which is transnet based segmentation...

**Comment by PaulDurai25** [comment]
Thanks in advance...I want to run latest ganav_rellis.py which is present in legacy/rellis_group6 folder. for this which one is corresponding pth file and I am getting same error i have posted earlier...

**Comment by rayguan97** [comment]
I think those pth are still accessible in the google drive under legacy_models/. The current version might not run those checkpoints. If you are still interested, please go back to previous commit (before July 25, 2022).

Those files are in the legacy folder and are not the latest ones with the best performance. If you are aiming for the best performance and efficient running time, please use the model that are not under legacy folder.
