### ISSUE TITLE
how to get segmentation cost map from segmentation results?

### ISSUE THREAD

**Issue by meiguiz** [rayguan97/GANav-offroad#19]
how to get segmentation cost map from segmentation results?I'm rather confused about this part, can you provide the code for this part?

**Comment by rayguan97** [comment]
We use a set of values from 0 to 1 for each semantic class. Then the cost values from the images are projected onto the ground plane and create a 2D cost map. This step should be straightforward. This is also explained in the paper.

In our implementation, we integrate it with TERP[1]. We superimpose our semantic cost with the cost map generated by TERP[1]. Please stay tuned for their code release.

[1] TERP: Reliable Planning in Uneven Outdoor Environments using Deep Reinforcement Learning

Please reopen the issue if you have further questions.
