### ISSUE TITLE
Own dataset

### ISSUE THREAD

**Issue by rock19970106** [rayguan97/GANav-offroad#2]
Dear Author,  is it suitable for RGD datasets in campus? if we apply  GANav-offroad to our own Kinect RGBD Campus Dataset, what we need to do?

**Comment by rock19970106** [comment]
okay, Thank you very much!

**Comment by rock19970106** [comment]
Hello,I want to infer  my dataset with your pre-trained models.  I only have some color images and how to use the script?

**Comment by rayguan97** [comment]
Here is a visualization script [here](https://github.com/rayguan97/GANav-offroad/blob/main/tools/visualize.py). 

All it needs it the dir of your image and the model weights and config.

**Comment by rock19970106** [comment]
img
checkpoints
config

if I use your pre-trained model rugd_group4 or rugd_group6 to inference my color images,  add these three , and run the visualization script? which parameters are need to modify in the config folder? such as  the image_width, image_height...

**Comment by rock19970106** [comment]
My image is 640*480

**Comment by rock19970106** [comment]
python ./tools/visualize.py img/000000.png trained_models/rugd_group4/ganav_campus.py trained_models/rugd_group4/ganav_rugd.pth
Use load_from_local loader
Traceback (most recent call last):
  File "./tools/visualize.py", line 40, in <module>
    main()
  File "./tools/visualize.py", line 32, in main
    result = inference_segmentor(model, img)
  File "/home/mist/GANav-offroad/mmseg/apis/inference.py", line 105, in inference_segmentor
    result= model(return_loss=False, rescale=True, **data)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/base.py", line 124, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/base.py", line 106, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 271, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 254, in inference
    seg_logit = self.whole_inference(img, img_meta, rescale)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 221, in whole_inference
    seg_logit = self.encode_decode(img, img_meta)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 87, in encode_decode
    x = self.extract_feat(img)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 79, in extract_feat
    x = self.backbone(img)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 772, in forward
    x = res_layer(x)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 389, in forward
    out = _inner_forward(x)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 366, in _inner_forward
    out, _ = self.conv2(out)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 171, in forward
    assert h==self.h
AssertionError

**Comment by rock19970106** [comment]
I only change the image size in ganav_campus according to th ganav_rugd.py. other else should be changed?

**Comment by rock19970106** [comment]
I only change the image size in the ganav_campus.py according to th ganav_rugd.py.  other else should be changed?

**Comment by rock19970106** [comment]
Here is my ganav_campus.py : 

norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained='open-mmlab://resnet50_v1c',
    backbone=dict(
        type='TransNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        norm_eval=False,
        style='pytorch',
        contract_dilation=True,
        head=4),
    decode_head=dict(
        type='OursHeadClassAtt',
        in_channels=2048,
        in_index=3,
        channels=512,
        mask_size=(97, 97),
        psa_type='bi-direction',
        compact=False,
        shrink_factor=2,
        normalization_factor=1.0,
        psa_softmax=True,
        dropout_ratio=0.1,
        num_classes=4,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss',
            use_sigmoid=False,
            loss_weight=1.0,
            static_weight=False)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=1024,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=4,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss',
            use_sigmoid=False,
            loss_weight=0.4,
            static_weight=False)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
dataset_type = 'RUGDDataset_Group4'
data_root = 'img/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
img_size = (640, 480)
crop_size = (300, 375)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(640, 480), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=(300, 375), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size=(300, 375), pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(300, 375),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    img_size=(300, 375),
    train=dict(
        type='RUGDDataset_Group4',
        data_root='data/rugd/',
        img_dir='RUGD_frames-with-annotations',
        ann_dir='RUGD_annotations',
        split='train_ours.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations'),
            dict(type='Resize', img_scale=(640, 480), ratio_range=(0.5, 2.0)),
            dict(type='RandomCrop', crop_size=(300, 375), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size=(300, 375), pad_val=0, seg_pad_val=255),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_semantic_seg'])
        ]),
    val=dict(
        type='RUGDDataset_Group4',
        data_root='img/',
        img_dir='RUGD_frames-with-annotations',
        ann_dir='RUGD_annotations',
        split='val_ours.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(300, 375),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='RUGDDataset_Group4',
        data_root='img/',
        img_dir='RUGD_frames-with-annotations',
        ann_dir='RUGD_annotations',
        split='test_ours.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(300, 375),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
log_config = dict(
    interval=50, hooks=[dict(type='TextLoggerHook', by_epoch=False)])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = './work_dirs/ours_class_att_group_rugd4/iter_160000.pth'
workflow = [('train', 1)]
cudnn_benchmark = True
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict()
lr_config = dict(policy='poly', power=0.9, min_lr=0.0001, by_epoch=False)
runner = dict(type='IterBasedRunner', max_iters=160000)
checkpoint_config = dict(by_epoch=False, interval=16000, max_keep_ckpts=5)
evaluation = dict(interval=16000, metric='mIoU')
work_dir = './work_dirs/ours_class_att_group_rugd4'
gpu_ids = range(0, 1)

**Comment by rock19970106** [comment]
My camera is Intel RealSense camera D435 too in real-world environments.

**Comment by rock19970106** [comment]
My camera is Intel RealSense camera too, D435 , in real-world environments.

**Comment by rock19970106** [comment]
can you send me the config for  real-world environments. my email is  2649085772@qq.com. Thank you very much.

**Comment by rayguan97** [comment]
The config you used is generated from those [files](https://github.com/rayguan97/GANav-offroad/tree/main/configs/ours). So some of the variables are already parsed to actual value. In order to use the modified config files provided in the google drive, you need to make sure that you changed all the values to the correct one, in your case, the img size.

For you case, with the example using rugd_group6, I suggest that you search for (688, 550), which is the img_size, and change all instances of (688, 550) to (640, 480). That should work.

**Comment by rock19970106** [comment]
Hello, thank you very much!

The config you provided in Google Drive is the same as your code files /trained_models/rugd_group6/ganav_rugd.py.

It include model, train_pipline, test_pipline, data(data_root, image_dir, ann_dir, split).

The visualize script you provided neeed img, config, model, checkpoint.  If I want to run this script directly, for example, give a single color image, output a segmented image. All these parametres(image_size, data_root, image_dir, ann_dir, split) should be changed? And run the visualization is okay(with the image path, config, checkpoint(ganav_rugd.pth) as the input parameters)?

**Comment by rayguan97** [comment]
To run training, you need to setup correct dir, but for inference, you don't need all of those. From my understanding, you just need to update img_size. I recommend you go through the code and experiment with it. Let me know if you run into any troubles.

**Comment by rock19970106** [comment]
Hi, I change the image_size.  And run the visualization script, also occurs some errors:

Use load_from_local loader
Traceback (most recent call last):
  File "./tools/visualize.py", line 39, in <module>
    main()
  File "./tools/visualize.py", line 32, in main
    result = inference_segmentor(model, img)
  File "/home/mist/GANav-offroad/mmseg/apis/inference.py", line 105, in inference_segmentor
    result= model(return_loss=False, rescale=True, **data)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/base.py", line 124, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/base.py", line 106, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 271, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 254, in inference
    seg_logit = self.whole_inference(img, img_meta, rescale)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 221, in whole_inference
    seg_logit = self.encode_decode(img, img_meta)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 87, in encode_decode
    x = self.extract_feat(img)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 79, in extract_feat
    x = self.backbone(img)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 772, in forward
    x = res_layer(x)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 389, in forward
    out = _inner_forward(x)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 366, in _inner_forward
    out, _ = self.conv2(out)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 171, in forward
    assert h==self.h
AssertionError

**Comment by rock19970106** [comment]
Hi, I change the img-size, and also occurs some errors:

Use load_from_local loader
Traceback (most recent call last):
  File "./tools/visualize.py", line 39, in <module>
    main()
  File "./tools/visualize.py", line 32, in main
    result = inference_segmentor(model, img)
  File "/home/mist/GANav-offroad/mmseg/apis/inference.py", line 105, in inference_segmentor
    result= model(return_loss=False, rescale=True, **data)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/base.py", line 124, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/base.py", line 106, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 271, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 254, in inference
    seg_logit = self.whole_inference(img, img_meta, rescale)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 221, in whole_inference
    seg_logit = self.encode_decode(img, img_meta)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 87, in encode_decode
    x = self.extract_feat(img)
  File "/home/mist/GANav-offroad/mmseg/models/segmentors/encoder_decoder.py", line 79, in extract_feat
    x = self.backbone(img)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 772, in forward
    x = res_layer(x)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 389, in forward
    out = _inner_forward(x)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 366, in _inner_forward
    out, _ = self.conv2(out)
  File "/mistgpu/miniconda/envs/ganav/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/GANav-offroad/mmseg/models/backbones/transnet.py", line 171, in forward
    assert h==self.h
AssertionError

**Comment by rayguan97** [comment]
Can you share the config you use? Have you make sure that you changed all instances of (688, 550) to (640, 480)?

**Comment by rayguan97** [comment]
Can you re-download the file in the google drive link? There was an update around August, and I just updated one to make sure. I downloaded the config from google drive and made the changes, everything worked fine.

**Comment by rock19970106** [comment]
Hi, I re-downloaded the config(rugd_group6)， the config(ganav_rugd.py) is the same as the ganav_rugd.py on the github ./trained_models/rugd_group6.

**Comment by rock19970106** [comment]
I indeed search the whole project to change all the (688, 550) to (640, 480). other else should be changed. I only use the visualization script to inference an image.

**Comment by rayguan97** [comment]
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained='open-mmlab://resnet50_v1c',
    backbone=dict(
        type='TransNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        norm_eval=False,
        style='pytorch',
        contract_dilation=True,
        head=4),
    decode_head=dict(
        type='OursHeadClassAtt',
        in_channels=2048,
        in_index=3,
        channels=512,
        mask_size=(97, 97),
        psa_type='bi-direction',
        compact=False,
        shrink_factor=2,
        normalization_factor=1.0,
        psa_softmax=True,
        dropout_ratio=0.1,
        num_classes=6,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss',
            use_sigmoid=False,
            loss_weight=1.0,
            static_weight=False)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=1024,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=6,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss',
            use_sigmoid=False,
            loss_weight=0.4,
            static_weight=False)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
dataset_type = 'RUGDDataset_Group6'
data_root = 'data/rugd/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
img_size = (640, 480)
crop_size = (300, 375)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(640, 480), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=(300, 375), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size=(300, 375), pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        # img_scale=(300, 375),
        img_sclae=(640, 480),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size=(300, 375), pad_val=0, seg_pad_val=255),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=2,
    img_size=(300, 375),
    train=dict(
        type='RUGDDataset_Group6',
        data_root='data/rugd/',
        img_dir='RUGD_frames-with-annotations',
        ann_dir='RUGD_annotations',
        split='train_ours.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations'),
            dict(type='Resize', img_scale=(640, 480), ratio_range=(0.5, 2.0)),
            dict(type='RandomCrop', crop_size=(300, 375), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size=(300, 375), pad_val=0, seg_pad_val=255),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_semantic_seg'])
        ]),
    val=dict(
        type='RUGDDataset_Group6',
        data_root='data/rugd/',
        img_dir='RUGD_frames-with-annotations',
        ann_dir='RUGD_annotations',
        split='val_ours.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(300, 375),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size=(300, 375), pad_val=0, seg_pad_val=255),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='RUGDDataset_Group6',
        data_root='data/rugd/',
        img_dir='RUGD_frames-with-annotations',
        ann_dir='RUGD_annotations',
        split='test_ours.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(300, 375),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size=(300, 375), pad_val=0, seg_pad_val=255),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
log_config = dict(
    interval=50, hooks=[dict(type='TextLoggerHook', by_epoch=False)])
dist_params = dict(backend='nccl')
log_level = 'INFO'
workflow = [('train', 1)]
cudnn_benchmark = True
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict()
lr_config = dict(policy='poly', power=0.9, min_lr=0.0001, by_epoch=False)
runner = dict(type='IterBasedRunner', max_iters=160000)
checkpoint_config = dict(by_epoch=False, interval=16000, max_keep_ckpts=5)
evaluation = dict(interval=16000, metric='mIoU')
gpu_ids = range(0, 1)

**Comment by rayguan97** [comment]
Use this one, let me know if it didn't work.

I personally use this to infer an image of size (640, 480). Please let me know whether it worked and where is the issue, in case I need to fix the repo or the config file.

**Comment by rock19970106** [comment]
okay, thank you very much

**Comment by rock19970106** [comment]
Hi, the config you just provided works well. Thank you very much. And I found that the only difference of the config you provided in Google Drive or Github  and you just provided is :

data = dict(

       val = dict(
              dict(type='Pad', size=(300, 375), pad_val=0, seg_pad_val=255),
         ) 

)

Hope it will help you to fix the repo or the config file.

Thanks for you kind patience. You did a great job.

**Comment by rayguan97** [comment]
Thank you! I’ll check it out and fix it in the repo!
