### ISSUE TITLE
Is the onnx file generated by pytorch2onnx.py quantized?

### ISSUE THREAD

**Issue by meiguiz** [rayguan97/GANav-offroad#21]
Is the onnx file generated by pytorch2onnx.py quantized?I use pytorch2onnx.py to get onnx,and then trans onnx to rknn.but i meet this problem?Do you know why?thank you very much!
![Screenshot from 2023-03-09 17-16-26](https://user-images.githubusercontent.com/90629126/223976147-ce0cc1cb-14ee-4503-9742-9e4f2c6449e6.png)

**Comment by rayguan97** [comment]
Our repo is based on [mmsegmentation](https://github.com/open-mmlab/mmsegmentation)](https://github.com/open-mmlab/mmsegmentation), and you can try to find similar issues in that repo. This is the [original file](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/pytorch2onnx.py) in MMSeg repo.
