### ISSUE TITLE
L1? L2? L3? 

### ISSUE THREAD

**Issue by hchoi71** [rayguan97/GANav-offroad#24]
In the paper, RUGD 6 groups consist of 'Smooth Region', 'Rough Region', 'Bumpy Region', 'Forbidden Region', 'Obstacle', 'Background'. 

When I run the test code, the output has shown as follows: Background, L1, L2, L3, non_Nav, obstacle. 

Could you please clarify which classes fall into which class described in the paper?

**Comment by rayguan97** [comment]
Thanks for pointing it out! I have updated the terminology, please pull the latest code.

**Comment by hchoi71** [comment]
Thanks!
