### ISSUE TITLE
checkpoint error

### ISSUE THREAD

**Issue by Zhangm0216** [rayguan97/GANav-offroad#25]
Hello.When I test on my own model trained by my dataset,there is a problem like that:test.py: error: the following arguments are required: checkpoint.What can I do for that? Thanks!

**Comment by rayguan97** [comment]
Hi,

Can you share the command you use? The checkpoint should be the model weights you trained with your own data. Both config and checkpoint(.pth) should be pass into the command.

Best,
Tianrui
________________________________
From: Zhangm0216 ***@***.***>
Sent: Monday, July 10, 2023 9:55:47 PM
To: rayguan97/GANav-offroad ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rayguan97/GANav-offroad] checkpoint error (Issue #25)


Hello.When I test on my own model trained by my dataset,there is a problem like that:test.py: error: the following arguments are required: checkpoint.What can I do for that? Thanks!

**Comment by Zhangm0216** [comment]
Thanks for your reply！


I am very glad that I have solved this problem. When I predicted on my own model, I found "visualize.py" in the GANav-offroad-main\tools path, but did not find the paths to img, config and checkpoint. I wonder if there are the paths to the above information when using "visualize.py" to predict, or should I write the code by myself?


Yours faithfully,
Zhangmian



Edward&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rayguan97/GANav-offroad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月12日(星期三) 凌晨2:18
***@***.***&gt;;
抄送:&nbsp;"Edward ***@***.******@***.***&gt;;
主题:&nbsp;Re: [rayguan97/GANav-offroad] checkpoint error (Issue #25)





 Hi, 
 
 Can you share the command you use? The checkpoint should be the model weights you trained with your own data. Both config and checkpoint(.pth) should be pass into the command. 
 
 Best, 
 Tianrui 
 ________________________________ 
 From: Zhangm0216 ***@***.***&gt; 
 Sent: Monday, July 10, 2023 9:55:47 PM 
 To: rayguan97/GANav-offroad ***@***.***&gt; 
 Cc: Subscribed ***@***.***&gt; 
 Subject: [rayguan97/GANav-offroad] checkpoint error (Issue #25) 
 
 
 Hello.When I test on my own model trained by my dataset,there is a problem like that:test.py: error: the following arguments are required: checkpoint.What can I do for that? Thanks!

**Comment by rayguan97** [comment]
Please check readme for all the data processing details. After preprocessing, you just need to point to the correct img, config and checkpoint.

**Comment by Zhangm0216** [comment]
Thanks for your answer！


Edward&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rayguan97/GANav-offroad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月13日(星期四) 凌晨3:57
***@***.***&gt;;
抄送:&nbsp;"Edward ***@***.******@***.***&gt;;
主题:&nbsp;Re: [rayguan97/GANav-offroad] checkpoint error (Issue #25)





 
Please check readme for all the data processing details. After preprocessing, you just need to point to the correct img, config and checkpoint.
