### ISSUE TITLE
Output image of the model

### ISSUE THREAD

**Issue by enginksz** [rayguan97/GANav-offroad#26]
Hello,

Thanks for sharing your work and code!

When I wanted to test and display the model's operation, I got the following results. When I experimented with different images, the result did not change. I could not provide the desired image from the dataset you provided.

Models I have used: ganav_rugd.pth and ganav_rugd_6.pth

I used these two models as you have given. I did not do the model training at this stage.

What would you recommend regarding the results?

Original image:
![park-1_00001](https://github.com/rayguan97/GANav-offroad/assets/38870269/7384d125-eaa0-4f3f-8916-11f344fa2579)

yours dataset :
![seg_park-1_00001](https://github.com/rayguan97/GANav-offroad/assets/38870269/baab3fe9-dbd0-4ba4-8e1b-9b2967b520c6)

output:
![Figure_1](https://github.com/rayguan97/GANav-offroad/assets/38870269/82090322-b9c8-4fb1-bce3-718c42e6ce2c)

**Comment by enginksz** [comment]
I think the model is trying to load pre-trained weights on a model with a different size than the original (ganav_rugd.pth)

If you can give me what the correct model is, I can try again.

**Comment by rayguan97** [comment]
Sorry about the delay! 

Can you try using the latest model following this link: https://drive.google.com/drive/folders/1PYn_kT0zBGOIRSaO_5Jivaq3itrShiPT?usp=sharing

Make sure you use the corresponding config in the same folder. Do not use ones in the legacy folder.
