### ISSUE TITLE
Change of backbone

### ISSUE THREAD

**Issue by sidharthnp** [rayguan97/GANav-offroad#28]
Is it possible to use a backbone model that is not listed in the directory. When I tried to implement it its telling its not present in the registry. I even tried adding it to the registry also still its not working out. What to do?

**Comment by rayguan97** [comment]
Yes, it's possible to add your own module, but you will need to modify several places.

Can you show me what changes have you made?

**Comment by rayguan97** [comment]
Closing due to stalel. Please reopen if you have more questions.
