### ISSUE TITLE
Training on GOOSE Dataset

### ISSUE THREAD

**Issue by rapzag** [rayguan97/GANav-offroad#29]
Thanks for this source code! We recently open sourced first parts of the [GOOSE dataset](https://goose-dataset.de/) and I trained GANav on the same.  

The qualitative results look quite promising but the numbers appear quite low compared to your results on RUGD and Rellis3D. Of course this is difficult to compare as no SOTA mIOU is established yet.

```
+-------+-------+-------+
|  aAcc |  mIoU |  mAcc |
+-------+-------+-------+
| 57.27 | 36.64 | 51.84 |
+-------+-------+-------+
+---------------------+-------+-------+
|        Class        |  IoU  |  Acc  |
+---------------------+-------+-------+
| background/obstacle | 71.94 | 73.34 |
|        stable       |  34.7 | 85.21 |
|       granular      | 15.96 | 23.93 |
|    poor foothold    | 21.94 | 32.33 |
|   high resistance   | 17.66 |  21.3 |
|         none        | 57.67 | 74.96 |
+---------------------+-------+-------+
```

I took the 6-class approach, with the following categorization and otherwise default parameters:

```
# 0 background: sky
# 1 Stable: bikeway, pedesstrian_crossing, road_marking, sidewalk, asphalt,
# 2 Granular: cobble, leaves, moss, gravel, soil
# 3 Poor foothold: snow, low_grass,
# 4 High resistance: high_grass, bush, debris, crops, water, tree_root
# 5 Obstacle: everything else
```

Do you have any tips for fine-tuning the training? If of interest, I could also add a PR with the config for GOOSE. 

https://github.com/rayguan97/GANav-offroad/assets/87997440/8db35fbe-159b-42d7-9dc3-e03b6bb39118

**Comment by rayguan97** [comment]
Hi,

Welcome to submit a PR to incorporate GOOSE dataset into the config and preparation steps in readme! 

Since I have not worked on this dataset, I do not have any experience or general tips on this dataset. You are also welcome to send me an email so we can discuss it further, once I have more details about this dataset. 

Best,
Tianrui

**Comment by rapzag** [comment]
There you go, I added some basic configuration. If you have time to try the training configuration, I would greatly appreciate some feedback on good parameters / mappings.

Best,
Raphael

**Comment by rayguan97** [comment]
Thank you for the pull request. It has been integrated into the repo. :)

**Comment by enginksz** [comment]
**How** can we **test** the model trained with the goose dataset? When I write a command like the one below, I get a "meta" error etc. Is there a procedure for testing?

command: python segmented_navigation.py ../trained_models/goose/ganav_group6_goose.py ../trained_models/goose/ddrnet_class_512.pth

error:   File "/home/eng/GANav-offroad/mmseg/apis/inference.py", line 39, in init_segmentor
    model.CLASSES = checkpoint['meta']['CLASSES']
KeyError: 'meta' 



Thanks

**Comment by rayguan97** [comment]
I didn't encounter this error before. If you use the same training scripts and the scripts to save the model, you shouldn't get this error. I think it just saved the number of classes during training.

Another suggestion is to check the config files. The "meta" key-value could come from the config files. Or you can hack it and hard code for now, if you just need to run it one time.

Let me know if those work.
