### ISSUE TITLE
output quality

### ISSUE THREAD

**Issue by xuyuxiu83** [rayguan97/GANav-offroad#32]
![IMG_2831(20240328-211422)](https://github.com/rayguan97/GANav-offroad/assets/126574371/a3b4c185-77a6-472e-b62a-f9e62688a37c)
I tested your model on a new dataset and scaled the images to the size of the RUGD dataset's images. The quality of the output results was very poor.

**Comment by rayguan97** [comment]
Can you try to finetune the model on this dataset with its original resolution? The segmentation may not work well if the camera angle and height are different.

**Comment by xuyuxiu83** [comment]
> Can you try to finetune the model on this dataset with its original resolution? The segmentation may not work well if the camera angle and height are different.

Thanks and I would give it a shot later.
