### ISSUE TITLE
User Guide / Usage

### ISSUE THREAD

**Issue by ryuchanhoe** [rayguan97/GANav-offroad#33]
Hey, thanks for sharing the work!

I was wondering the expected usage / instruction of this for the users.

This seems to be working but the results are not that satisfying.

 So I was wondering,
 1. I believe the trained model that you shared is fully  trained on the dataset in train_ours.txt. 
Therefore, there is no need for us the Dataset Processing and Training in the Get Started tutorial?
 2. Do you expect the users to create their custom data set and finetune the model for better performance? 
 3. If so, I was wondering if you have an instruction for making RUGD custom dataset? 
  
This is the experimental image, that I ran RUGD6 model on my camera data that I acquired.
FYI, I am planning to utilize this for terrain segmentation for a buggy car. 
My hardware setup is not identical to yours, mine is parallel to the ground, 30cm above the ground, not inclined toward the ground. 

![image](https://github.com/rayguan97/GANav-offroad/assets/46981975/1ba43a16-206a-4504-b765-3153acf6ed5a)

![extrapolated output_screenshot_12 04 2024](https://github.com/rayguan97/GANav-offroad/assets/46981975/8fba2eae-1225-43ad-9eaf-40c6960ec093)

Thanks in advance!

**Comment by rayguan97** [comment]
Thank you for your interest!

1. Correct. If you do not plan to retrain the model using RUGD and RELLIS, no need to run data preprocessing.
2. Yes. If the angle and the height from the ground are different, you might need to retrain it with your own dataset. We have not explore much its domain adaptation capability, other than doing some navigation testing in our environment. We did notice that the performance is not as good in real-world compared to the results on the dataset, so you should be able to get better results if you build a custom dataset and finetune it.
3. I don't have an instruction provided, but if you go through the code, it should be straight forward. You can try to put the data in an existing dataset format and copy the code. You may need to adjust the name of the dataset and classes in a few places.

Best,

**Comment by ryuchanhoe** [comment]
Thanks for the reply.
Yeah, I was able to create custom dataset.
I might get back to you as I progress!
