### ISSUE TITLE
RUGD xxx.txt

### ISSUE THREAD

**Issue by linchangyi1** [rayguan97/GANav-offroad#6]
The documents test_ours.txt, train_ours.txt and val_ours.txt are required in the rugd_relabel4.py and rugd_relabel6.py. However, they don't exist in the RUGD Dataset which can be downloaded in http://rugd.vision/. Therefore, I want to sincerely ask how did you get these three documents.

**Comment by linchangyi1** [comment]
Hi, thank you for your opensource.
Several days ago, I used your source code and successfully run the train.py file. However, without any change of the code, I can't run it again and meet these error. So I installed your source again and also try on other computers, even transport your file to new mmsegmentation framwork, but still met the same error. I suppose the errors come from the change of mmcv. But I really don't know how to modify the code. Could you please tell me how to modify it. The errors are(I am sure I put the RUGD data in the right place):


"""
Traceback (most recent call last):
  File "/home/changyilin/lib/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/changyilin/Final_Project/SSDMUE/mmsegmentation/mmseg/datasets/rugd.py", line 61, in __init__
    **kwargs)
  File "/home/changyilin/Final_Project/SSDMUE/mmsegmentation/mmseg/datasets/custom.py", line 124, in __init__
    self.seg_map_suffix, self.split)
  File "/home/changyilin/Final_Project/SSDMUE/mmsegmentation/mmseg/datasets/custom.py", line 149, in load_annotations
    with open(split) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/rugd/train_ours.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/changyilin/Final_Project/SSDMUE/mmsegmentation/tools/train.py", line 172, in <module>
    main()
  File "/home/changyilin/Final_Project/SSDMUE/mmsegmentation/tools/train.py", line 145, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/changyilin/Final_Project/SSDMUE/mmsegmentation/mmseg/datasets/builder.py", line 83, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/changyilin/lib/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: UnstructureDataset: [Errno 2] No such file or directory: 'data/rugd/train_ours.txt'
"""

**Comment by rayguan97** [comment]
This is strange -- have you made sure that "data/rugd/train_ours.txt" exists?

**Comment by linchangyi1** [comment]
Yes, I put them in the right place and can run successfully once but failed days later.
![image](https://user-images.githubusercontent.com/71823391/159388774-a641fa85-48aa-4182-80ce-a8224d0a8857.png)
-----------------------------------------------------------------------------------
Besides, I also tried other methods:
1. change the relative "data_root" into an absolute one, meaning from

**Comment by linchangyi1** [comment]
Yes, I put them in the right place and ran it successfully once but failed days later.
![image](https://user-images.githubusercontent.com/71823391/159389088-b067709c-1f62-4015-b908-69fa554dea34.png)
-----------------------------------------------
Besides, I also tried other methods:

1. I changed the data_root from a relative root to an absolute one, meaning
from data_root = 'data/rugd' to data_root = '~/Final_Project/SSDMUE/mmsegmentation/data/rugd'
but still met error: No such file or directory: '~/Final_Project/SSDMUE/mmsegmentation/data/rugd/train_ours.txt'

2. I chose not to use split but directly change the img_dir and ann_dir to the specify one, and deleted split="train_ours.txt", 
like:
![image](https://user-images.githubusercontent.com/71823391/159389708-afe424b2-db98-4c95-a712-d09f1d4c5fed.png)
but still met error: No such file or directory: 'data/rugd/creek'

3. I installed your code in other computers from one step to one, but still met the error like the first one.

**Comment by rayguan97** [comment]
This is really strange. I just made a fresh git clone and it seems that it's working properly for me.

There are a couple of suggestions:
1. Have you make sure that the directory is not empty here, or the file indeed exists -- "home/linchangyi/Final_Project/SSDMUE/mmsegmentation/data/rugd/train_ours.txt"? This error seems quite straight forward -- the code could not find this file.
2. It's possible that the mmseg is messed up in the environment. Have you tried using conda env and tried creating a fresh env for GANav? Previously when I put different versions of my code in different places, I have to run "pip install -e ." to make sure that it's using the repo I intend to.
3. Have you made sure that you pulled the latest version of the code?

**Comment by linchangyi1** [comment]
Thanks for your trying and suggestions.
I will try it again in new environment.
