### ISSUE TITLE
RUGD Dataset

### ISSUE THREAD

**Issue by linchangyi1** [rayguan97/GANav-offroad#7]
I can find the "/convert_datasets" dir. But where could I find these six documents(in the official website of RUGD Dataset, I can only download the dirs "/RUGD_annotations" and "/RUGD_frames-with-annotations" but CAN NOT find the documents below): 
│   │   │── test_ours.txt
│   │   │── test.txt
│   │   │── train_ours.txt
│   │   │── train.txt
│   │   │── val_ours.txt
│   │   │── val.txt

Do I need to make them by myself, or could you please release them.

**Comment by rayguan97** [comment]
You can find those files [here](https://github.com/rayguan97/GANav-offroad/tree/main/data/rugd), if you follow the instruction.
