### ISSUE TITLE
Error while training the rellis model on group 6

### ISSUE THREAD

**Issue by mayureshb7** [rayguan97/GANav-offroad#9]
Hey all of the setups went well when I followed the steps for the rellis data set.
I created the environment and was able to run the data processing step successfully. however, I was getting an error while running the training step for rellis which is 

training step:
 python ./tools/train.py ./configs/ours/ganav_group6_rellis.py

error:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/99101076/163724816-825232c6-32d3-4588-b59a-890ba09599b7.png">

Are you familiar with the initialization of _get_default_group and do you know how to resolve this

**Comment by rayguan97** [comment]
May I know more about your training setting? For example, how many GPUs were you using? Are they on the same node or they are in multiple nodes. 

I have never run into this issue, my training setting was 1, 2 or 4 gpus at the same time on the same machine. If you could provide more details, I could try to reproduce the error and see what’s the issue.

**Comment by mayureshb7** [comment]
I'm running it on the Palmetto cluster to which access is provided by my University
following is the image of the specs I used in my Jupyter Notebook 
<img width="475" alt="image" src="https://user-images.githubusercontent.com/99101076/163728378-bf08ac74-fc4a-443b-a85b-f84e9b18aa28.png">

**Comment by rayguan97** [comment]
Since I’m not very familiar with your university cluster, I recommend that you try running it on one gpu first. I have no issue running this code with 2 GPUs.

Please let me know if you have more questions!

**Comment by LancerXE** [comment]
I think the issue comes from using single GPU running, it can be solved by changing `norm_cfg = dict(type='SyncBN', requires_grad=True)` 
to `norm_cfg = dict(type='BN', requires_grad=True)` in /_base_/models/ours_class_att.py
Here is an identical issue [#902](https://github.com/open-mmlab/mmsegmentation/issues/902).
